# deploys into AWS infra - with cloudformation template - uses api gteway and lambda
language: node_js

node_js:
  - "5.11"

env:
  - DEPLOY_ENV=dev

script:
  npm run build

before_deploy:
   pip install --user awscli

deploy:
  - provider: script
    script: npm run prepdeploy
    skip_cleanup: true
  - provider: script
    script: npm run deploy
    skip_cleanup: true

notifications:
    email:
        on_failure: always
