# Root File for non cdn based cloud formation template
#
AWSTemplateFormatVersion: '2010-09-09'
Description: "API Infrastructure CF Template"
Parameters:
  $ref: ../../scripts/aws-cfn/parameters/index.yaml
Mappings:
  RegionMap:
    $ref: ../../scripts/aws-cfn/mappings/region-map.yaml
  HostedZones:
    $ref: ../../scripts/aws-cfn/mappings/hosted-zones.yaml
Conditions:
  $ref: ../../scripts/aws-cfn/conditions/is-prod-env.yaml
Resources:
  $ref: ../../scripts/aws-cfn/resources/index.yaml
Outputs:
  $ref: ../../scripts/aws-cfn/outputs/index.yaml
